export const errorCategory = {
  CRITICAL: 'CRITICAL',
  LOGIN_ERROR: 'LOGIN_ERROR',
  RECOVERABLE_ERROR: 'RECOVERABLE_ERROR',
  NON_RECOVERABLE_ERROR: 'NON_RECOVERABLE_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  MULTI_CHOICE_DIALOG: 'MULTI_CHOICE_DIALOG',
  OTHER_GAME_IN_PROGRESS: 'OTHER_GAME_IN_PROGRESS',
  REALITY_CHECK: 'REALITY_CHECK',
  REALITY_CHECK_COOKIE: 'REALITY_CHECK_COOKIE'
};

export const errorSeverity = {
  WARNING: 'WARNING',
  INFO: 'INFO',
  ERROR: 'ERROR'
};

export const ogsapierrorCode = {
  INSUFFICIENT_FUNDS: 'OGS.1006',
  LOGIN_ERROR: 'OGS.1000',
  GAMING_LIMIT: 'OGS.1019',
  LOCKED_ACCOUNT: 'OGS.1035',
  REALITY_CHECK: 'OGS.1109'
};




// WEBPACK FOOTER //
// ./src/main/errormap.js